language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install: "pip install -r dev-requirements.txt"

# command to run tests
script:
 - cp festcms/settings.py.example festcms/settings.py
 - coala --ci
 - python manage.py test
 - coverage run --source='festflow' manage.py test
 - coverage report

after_success:
 - codecov
